import { v4 as uuidv4 } from 'uuid';
const leathers = [
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted ',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Brown',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 29500,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
        
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },
    {
        id: uuidv4(),
        type: "leather",
        name: 'Black Spotted Leather',
        imageSrc: 'https://media.istockphoto.com/id/1166715036/photo/red-cotton-linen-fabric-seamless-texture.webp?b=1&s=170667a&w=0&k=20&c=ITijY6GHsrkcblJrfoVwaFoZzOy94WjGY6Bqp8lS5KA=',
        imageAlt: "Front of men's Basic Tee in black.",
        price: 22680,
        price1: 29500,
        color: 'Black',
    },

];
export default leathers;